AllCops:
  Exclude:
    - vendor/**/*

TrailingComma:
  Enabled: false

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

ClassLength:
  Max: 125

LineLength:
  Enabled: false
